# Churn Prediction Inference - Batch or serverless real-time


With AutoML, our best model was automatically saved in our MLFlow registry.

All we need to do now is use this model to run Inferences. A simple solution is to share the model name to our Data Engineering team and they'll be able to call this model within the pipeline they maintained. That's what we did in our Spark Declarative Pipelines pipeline!

Alternatively, this can be schedule in a separate job. Here is an example to show you how MLFlow can be directly used to retriver the model and run inferences.

<!-- Collect usage data (view). Remove it to disable collection or disable tracker during installation. View README for more details.  -->
<img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=lakehouse&org_id=2162748966026566&notebook=%2F04-Data-Science-ML%2F04.3-running-inference&demo_name=lakehouse-retail-c360&event=VIEW&path=%2F_dbdemos%2Flakehouse%2Flakehouse-retail-c360%2F04-Data-Science-ML%2F04.3-running-inference&version=1">

In [0]:
%pip install mlflow==3.1.0
dbutils.library.restartPython()

Collecting mlflow==3.1.0
  Using cached mlflow-3.1.0-py3-none-any.whl.metadata (29 kB)
Collecting mlflow-skinny==3.1.0 (from mlflow==3.1.0)
  Using cached mlflow_skinny-3.1.0-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: Flask<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (2.2.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (1.14.1)
Collecting docker<8,>=4.0.0 (from mlflow==3.1.0)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow==3.1.0)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: gunicorn<24 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (20.1.0)
Requirement already satisfied: matplotlib<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (3.8.4)
Requirement already satisfied: numpy<3 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (1.26.4)
Requirement already satisfied: pandas<3 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (1.5.3)
Requirement already satisfied: pyarrow<21,>=4.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (15.0.2)
Requirement already satisfied: scikit-learn<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (1.4.2)
Requirement already satisfied: scipy<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (1.13.1)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0) (2.0.30)
Requirement already satisfied: cachetools<7,>=5.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (8.1.7)
Requirement already satisfied: cloudpickle<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (2.2.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (0.30.0)
Requirement already satisfied: fastapi<1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (0.115.12)
Requirement already satisfied: gitpython<4,>=3.1.9 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (3.1.37)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (6.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (1.32.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (1.32.0)
Requirement already satisfied: packaging<26 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (24.1)
Requirement already satisfied: protobuf<7,>=3.12.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (4.24.1)
Requirement already satisfied: pydantic<3,>=1.10.8 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (2.8.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (6.0.1)
Requirement already satisfied: requests<3,>=2.17.3 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (2.32.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (0.4.2)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (4.11.0)
Requirement already satisfied: uvicorn<1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0) (0.34.1)
Requirement already satisfied: Mako in /databricks/python3/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow==3.1.0) (1.2.0)
Requirement already satisfied: urllib3>=1.26.0 in /databricks/python3/lib/python3.12/site-packages (from docker<8,>=4.0.0->mlflow==3.1.0) (1.26.16)
Requirement already satisfied: Werkzeug>=2.2.2 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==3.1.0) (3.0.3)
Requirement already satisfied: Jinja2>=3.0 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==3.1.0) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==3.1.0) (2.2.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /databricks/python3/lib/python3.12/site-packages (from graphene<4->mlflow==3.1.0) (3.2.4)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow==3.1.0)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /databricks/python3/lib/python3.12/site-packages (from graphene<4->mlflow==3.1.0) (2.9.0.post0)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.12/dist-packages (from gunicorn<24->mlflow==3.1.0) (74.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==3.1.0) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==3.1.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==3.1.0) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==3.1.0) (1.4.4)
Requirement already satisfied: pillow>=8 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==3.1.0) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==3.1.0) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.12/site-packages (from pandas<3->mlflow==3.1.0) (2024.1)
Requirement already satisfied: joblib>=1.2.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn<2->mlflow==3.1.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn<2->mlflow==3.1.0) (2.2.0)
Requirement already satisfied: greenlet!=0.4.17 in /databricks/python3/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==3.1.0) (3.0.1)
Requirement already satisfied: google-auth~=2.0 in /databricks/python3/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (2.21.0)
Requirement already satisfied: starlette<0.47.0,>=0.40.0 in /databricks/python3/lib/python3.12/site-packages (from fastapi<1->mlflow-skinny==3.1.0->mlflow==3.1.0) (0.46.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /databricks/python3/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.1.0->mlflow==3.1.0) (4.0.11)
Requirement already satisfied: zipp>=0.5 in /databricks/python3/lib/python3.12/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python3/lib/python3.12/site-packages (from Jinja2>=3.0->Flask<4->mlflow==3.1.0) (2.1.3)
Requirement already satisfied: deprecated>=1.2.6 in /databricks/python3/lib/python3.12/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (1.2.18)
Requirement already satisfied: opentelemetry-semantic-conventions==0.53b0 in /databricks/python3/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (0.53b0)
Requirement already satisfied: annotated-types>=0.4.0 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow==3.1.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow==3.1.0) (2.20.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow==3.1.0) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow==3.1.0) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow==3.1.0) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow==3.1.0) (2024.6.2)
Requirement already satisfied: h11>=0.8 in /databricks/python3/lib/python3.12/site-packages (from uvicorn<1->mlflow-skinny==3.1.0->mlflow==3.1.0) (0.14.0)
Requirement already satisfied: wrapt<2,>=1.10 in /databricks/python3/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (1.14.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /databricks/python3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.1.0->mlflow==3.1.0) (5.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /databricks/python3/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /databricks/python3/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (4.9)
Requirement already satisfied: anyio<5,>=3.6.2 in /databricks/python3/lib/python3.12/site-packages (from starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.0->mlflow==3.1.0) (4.2.0)
Requirement already satisfied: sniffio>=1.1 in /databricks/python3/lib/python3.12/site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.0->mlflow==3.1.0) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /databricks/python3/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0) (0.4.8)
Using cached mlflow-3.1.0-py3-none-any.whl (24.7 MB)
Using cached mlflow_skinny-3.1.0-py3-none-any.whl (1.9 MB)
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: graphql-relay, graphene, docker, mlflow-skinny, mlflow
  Attempting uninstall: mlflow-skinny
    Found existing installation: mlflow-skinny 2.21.3
    Not uninstalling mlflow-skinny at /databricks/python3/lib/python3.12/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-4311a605-a91a-4cd6-a004-b257abf9fe9d
    Can't uninstall 'mlflow-skinny'. No files were found to uninstall.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
databricks-feature-engineering 0.10.2 requires mlflow-skinny[databricks]<3,>=2.16.0, but you have mlflow-skinny 3.1.0 which is incompatible.
Successfully installed docker-7.1.0 graphene-3.4.3 graphql-relay-3.2.0 mlflow-3.1.0 mlflow-skinny-3.1.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
%run ../_resources/00-setup $reset_all_data=false

USE CATALOG `main__build`
using catalog.database `main__build`.`dbdemos_retail_c360`

data already existing. Run with reset_all_data=true to force a data cleanup for your local demo.

##Deploying the model for batch inferences

Now that our model is available in the Registry, we can load it to compute our inferences and save them in a table to start building dashboards.

We will use MLFlow function to load a pyspark UDF and distribute our inference in the entire cluster. If the data is small, we can also load the model with plain python and use a pandas Dataframe.

### Scaling inferences using Spark 
We'll first see how it can be loaded as a spark UDF and called directly in a SQL function:

In [0]:
import mlflow
model_name = "dbdemos_customer_churn"
mlflow.set_registry_uri("databricks-uc")
#                                                                                                Alias
#                                                                                  Model name       |
#                                                                                        |          |
predict_churn_udf = mlflow.pyfunc.spark_udf(spark, model_uri=f"models:/{catalog}.{db}.{model_name}@prod", env_manager='virtualenv', result_type='long')
# Note: virtualenv will recreate an env from scratch which can take some time, but prevent any version issue. If you're using the same compute as for training, you can remove it to use the local env instead (just install the lib from the requirements.txt file as below)
#We can use the function in SQL
spark.udf.register("predict_churn", predict_churn_udf)

Downloading artifacts:   0%|          | 0/12 [00:00<?, ?it/s]

2025/12/09 16:56:34 INFO mlflow.pyfunc: This UDF will use virtualenv to recreate the model's software environment for inference. This may take extra time during execution.

Downloading artifacts:   0%|          | 0/12 [00:00<?, ?it/s]

2025/12/09 16:56:34 INFO mlflow.models.flavor_backend_registry: Selected backend for flavor 'python_function'
2025/12/09 16:56:34 INFO mlflow.utils.virtualenv: Installing python 3.12.3 if it does not exist
2025/12/09 16:57:49 INFO mlflow.utils.virtualenv: Creating a new environment in /local_disk0/.ephemeral_nfs/repl_tmp_data/ReplId-19b03-f841a-1/mlflow/envs/virtualenv_envs/mlflow-2e7e6045218a336288d5eded6dc6233a3bccf3c4 with /local_disk0/.ephemeral_nfs/repl_tmp_data/ReplId-19b03-f841a-1/mlflow/envs/pyenv_root/versions/3.12.3/bin/python
2025/12/09 16:57:49 INFO mlflow.utils.virtualenv: Installing dependencies
2025/12/09 16:58:41 INFO mlflow.utils.environment: === Running command '['bash', '-c', 'source /local_disk0/.ephemeral_nfs/repl_tmp_data/ReplId-19b03-f841a-1/mlflow/envs/virtualenv_envs/mlflow-2e7e6045218a336288d5eded6dc6233a3bccf3c4/bin/activate && python -c ""']'

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

In [0]:
columns = predict_churn_udf.metadata.get_input_schema().input_names()
spark.table('churn_features').withColumn("churn_prediction", predict_churn_udf(*columns)).display()

### Pure pandas inference
If we have a small dataset, we can also compute our segment using a single node and pandas API:

In [0]:
from mlflow.store.artifact.models_artifact_repo import ModelsArtifactRepository
import mlflow
# Use the Unity Catalog model registry
mlflow.set_registry_uri("databricks-uc")
# download model requirement from remote registry
requirements_path = ModelsArtifactRepository(f"models:/{catalog}.{db}.dbdemos_customer_churn@prod").download_artifacts(artifact_path="requirements.txt")

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

In [0]:
%pip install -r $requirements_path
dbutils.library.restartPython()

Requirement already satisfied: mlflow==3.1.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4311a605-a91a-4cd6-a004-b257abf9fe9d/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: category-encoders==2.6.3 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 2)) (2.6.3)
Requirement already satisfied: cffi==1.16.0 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: cloudpickle==2.2.1 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 4)) (2.2.1)
Requirement already satisfied: databricks-automl-runtime==0.2.21 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 5)) (0.2.21)
Requirement already satisfied: defusedxml==0.7.1 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 6)) (0.7.1)
Requirement already satisfied: holidays==0.54 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 7)) (0.54)
Requirement already satisfied: lightgbm==4.5.0 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 8)) (4.5.0)
Requirement already satisfied: lz4==4.3.2 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 9)) (4.3.2)
Requirement already satisfied: matplotlib==3.8.4 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (3.8.4)
Requirement already satisfied: numpy==1.26.4 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 11)) (1.26.4)
Collecting pandas==2.2.3 (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 12))
  Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Requirement already satisfied: psutil==5.9.0 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 13)) (5.9.0)
Requirement already satisfied: pyarrow==15.0.2 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 14)) (15.0.2)
Requirement already satisfied: scikit-learn==1.4.2 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 15)) (1.4.2)
Requirement already satisfied: scipy==1.13.1 in /databricks/python3/lib/python3.12/site-packages (from -r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 16)) (1.13.1)
Requirement already satisfied: mlflow-skinny==3.1.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4311a605-a91a-4cd6-a004-b257abf9fe9d/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: Flask<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.2.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.14.1)
Requirement already satisfied: docker<8,>=4.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4311a605-a91a-4cd6-a004-b257abf9fe9d/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (7.1.0)
Requirement already satisfied: graphene<4 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4311a605-a91a-4cd6-a004-b257abf9fe9d/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.4.3)
Requirement already satisfied: gunicorn<24 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (20.1.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.0.30)
Requirement already satisfied: statsmodels>=0.9.0 in /databricks/python3/lib/python3.12/site-packages (from category-encoders==2.6.3->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 2)) (0.14.2)
Requirement already satisfied: patsy>=0.5.1 in /databricks/python3/lib/python3.12/site-packages (from category-encoders==2.6.3->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 2)) (0.5.6)
Requirement already satisfied: pycparser in /databricks/python3/lib/python3.12/site-packages (from cffi==1.16.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 3)) (2.21)
Requirement already satisfied: python-dateutil in /databricks/python3/lib/python3.12/site-packages (from holidays==0.54->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 7)) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (24.1)
Requirement already satisfied: pillow>=8 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib==3.8.4->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 10)) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.12/site-packages (from pandas==2.2.3->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 12)) (2024.1)
Collecting tzdata>=2022.7 (from pandas==2.2.3->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 12))
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: joblib>=1.2.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn==1.4.2->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 15)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn==1.4.2->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 15)) (2.2.0)
Requirement already satisfied: cachetools<7,>=5.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (8.1.7)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.30.0)
Requirement already satisfied: fastapi<1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.115.12)
Requirement already satisfied: gitpython<4,>=3.1.9 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.1.37)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (6.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.32.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.32.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (4.24.1)
Requirement already satisfied: pydantic<3,>=1.10.8 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: requests<3,>=2.17.3 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.32.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (4.11.0)
Requirement already satisfied: uvicorn<1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.34.1)
Requirement already satisfied: Mako in /databricks/python3/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: urllib3>=1.26.0 in /databricks/python3/lib/python3.12/site-packages (from docker<8,>=4.0.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.26.16)
Requirement already satisfied: Werkzeug>=2.2.2 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: Jinja2>=3.0 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /databricks/python3/lib/python3.12/site-packages (from graphene<4->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.2.4)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-4311a605-a91a-4cd6-a004-b257abf9fe9d/lib/python3.12/site-packages (from graphene<4->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.12/dist-packages (from gunicorn<24->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (74.0.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from patsy>=0.5.1->category-encoders==2.6.3->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: greenlet!=0.4.17 in /databricks/python3/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: google-auth~=2.0 in /databricks/python3/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: starlette<0.47.0,>=0.40.0 in /databricks/python3/lib/python3.12/site-packages (from fastapi<1->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.46.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /databricks/python3/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (4.0.11)
Requirement already satisfied: zipp>=0.5 in /databricks/python3/lib/python3.12/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python3/lib/python3.12/site-packages (from Jinja2>=3.0->Flask<4->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: deprecated>=1.2.6 in /databricks/python3/lib/python3.12/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.2.18)
Requirement already satisfied: opentelemetry-semantic-conventions==0.53b0 in /databricks/python3/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.53b0)
Requirement already satisfied: annotated-types>=0.4.0 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3,>=1.10.8->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (2024.6.2)
Requirement already satisfied: h11>=0.8 in /databricks/python3/lib/python3.12/site-packages (from uvicorn<1->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.14.0)
Requirement already satisfied: wrapt<2,>=1.10 in /databricks/python3/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.14.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /databricks/python3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (5.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /databricks/python3/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /databricks/python3/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (4.9)
Requirement already satisfied: anyio<5,>=3.6.2 in /databricks/python3/lib/python3.12/site-packages (from starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (4.2.0)
Requirement already satisfied: sniffio>=1.1 in /databricks/python3/lib/python3.12/site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /databricks/python3/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.0->mlflow==3.1.0->-r /local_disk0/repl_tmp_data/ReplId-19b03-f841a-1/tmpy8g2ruu_/requirements.txt (line 1)) (0.4.8)

In [0]:
%run ../_resources/00-setup $reset_all_data=false

USE CATALOG `main__build`
using catalog.database `main__build`.`dbdemos_retail_c360`

data already existing. Run with reset_all_data=true to force a data cleanup for your local demo.

In [0]:
import mlflow
mlflow.set_registry_uri("databricks-uc")
model_name = "dbdemos_customer_churn"
model = mlflow.pyfunc.load_model(f"models:/{catalog}.{db}.{model_name}@prod")
columns = model.metadata.get_input_schema().input_names()
df = spark.table('churn_features').select(*columns).limit(10).toPandas()
df['churn_prediction'] = model.predict(df)
df.head(3)

Downloading artifacts:   0%|          | 0/12 [00:00<?, ?it/s]

[LightGBM] [Warning] lambda_l2 is set=117.97769127793491, reg_lambda=0.0 will be ignored. Current value: lambda_l2=117.97769127793491
[LightGBM] [Warning] lambda_l1 is set=0.24114681074974328, reg_alpha=0.0 will be ignored. Current value: lambda_l1=0.24114681074974328

                                user_id  ... churn_prediction
0  ccbd668a-50b1-485c-bb82-7b994fed0fd7  ...                0
1  509b3da6-c25a-4b9a-b375-5ade442b95c2  ...                0
2  a46211c0-d5d5-4067-9993-f23555724281  ...                1

[3 rows x 16 columns]


## Realtime model serving with Databricks serverless serving

<img style="float: right; margin-left: 20px" width="700" src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/retail/lakehouse-churn/lakehouse-c360-model-serving.png?raw=true" />

Databricks also provides serverless serving.

Click on model Serving, enable realtime serverless and your endpoint will be created, providing serving over REST api within a Click.

Databricks Serverless offer autoscaling, including downscaling to zero when you don't have any traffic to offer best-in-class TCO while keeping low-latencies model serving.

To deploy your serverless model, open the [Model Serving menu](https://xxxx.cloud.databricks.com/?o=1660015457675682#mlflow/endpoints), and select the model you registered within Unity Catalog.

In [0]:
from mlflow.deployments import get_deploy_client
model_endpoint_name = "dbdemos_customer_churn_endpoint"
last_version = get_last_model_version(f"{catalog}.{db}.{model_name}")
client = get_deploy_client("databricks")
try:
    endpoint = client.create_endpoint(
        name=model_endpoint_name,
        config={
            "served_entities": [
                {
                    "name": f"dbdemos_customer_churn_endpoint_{last_version}",
                    "entity_name": f"{catalog}.{db}.{model_name}",
                    "entity_version": last_version,
                    "workload_size": "Small",
                    "scale_to_zero_enabled": True
                }
            ]
        }
    )
except Exception as e:
    if "already exists" in str(e).lower():
        print(f"Endpoint {catalog}.{db}.{model_endpoint_name} already exists. Skipping creation.")
    else:
        raise e

while client.get_endpoint(model_endpoint_name)['state']['config_update'] == 'IN_PROGRESS':
    time.sleep(10)

Endpoint main.dbdemos_retail_c360.dbdemos_customer_churn_endpoint already exists. Skipping creation.

In [0]:
dataset = spark.table('churn_features').select(*columns).limit(3).toPandas()
#Make it a string to send to the inference endpoint
dataset['last_transaction'] = dataset['last_transaction'].astype(str)
dataset

                                user_id  ... days_last_event
0  ccbd668a-50b1-485c-bb82-7b994fed0fd7  ...             920
1  509b3da6-c25a-4b9a-b375-5ade442b95c2  ...             916
2  a46211c0-d5d5-4067-9993-f23555724281  ...             915

[3 rows x 15 columns]

In [0]:
from mlflow import deployments

def score_model(dataset):
  client = mlflow.deployments.get_deploy_client("databricks")
  payload = {"dataframe_split": dataset.to_dict(orient='split')}
  predictions = client.predict(endpoint=model_endpoint_name, inputs=payload)
  print(predictions)

#Deploy your model and uncomment to run your inferences live!
score_model(dataset)

{'predictions': [0, 0, 1]}


# Next step: Leverage inferences and automate actions to increase revenue

## Automate action to reduce churn based on predictions

We now have an end 2 end data pipeline analizing and predicting churn. We can now easily trigger actions to reduce the churn based on our business:

- Send targeting email campaign to the customer the most likely to churn
- Phone campaign to discuss with our customers and understand what's going
- Understand what's wrong with our line of product and fixing it

These actions are out of the scope of this demo and simply leverage the Churn prediction field from our ML model.

## Track churn impact over the next month and campaign impact

Of course, this churn prediction can be re-used in our dashboard to analyse future churn and measure churn reduction. 

The pipeline created with the Lakehouse will offer a strong ROI: it took us a few hours to setup this pipeline end 2 end and we have potential gain for $129,914 / month!

<img width="800px" src="https://raw.githubusercontent.com/QuentinAmbard/databricks-demo/main/retail/resources/images/lakehouse-retail/lakehouse-retail-churn-dbsql-prediction-dashboard.png">

<a dbdemos-dashboard-id="churn-prediction" href='/sql/dashboardsv3/01f1b2d441601962affad7fdce91ca8e'>Open the Churn prediction DBSQL dashboard</a>


## Reducing churn leveraging Databricks GenAI and LLMs capabilities 

GenAI provides unique capabilities to improve your customer relationship, providing better services but also better analyzing your churn risk.

Databricks provides built-in GenAI capabilities for you to accelerate such GenAI apps deployment. 

Discover how with the [Agent Tools]($../05-Generative-AI/05.1-Agent-Functions-Creation) Notebook in the new Generative AI section of this demo!

[Go back to the introduction]($../00-churn-introduction-lakehouse)